# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

matrix:
  include:
    - jdk: oraclejdk8
      # Sanity regression tests with major supported Gradle versions
      env: SHIPKIT_REGRESSION_TESTS=quick

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build testDownstream -PcheckJava6Compatibility --daemon -s -i && ./gradlew ciPerformRelease

# Remove often changing files to prevent cache re-upload on no changes in dependencies
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -fr $HOME/.gradle/caches/transforms-1/transforms-1.lock
  - rm -fr $HOME/.gradle/caches/jars-*/*/shipkit-*.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

