# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

matrix:
  include:
    - jdk: oraclejdk8
      # Sanity regression tests with major supported Gradle versions
      env: SHIPKIT_REGRESSION_TESTS=quick

#don't build tags
branches:
  except:
  - /^v\d/

install:
  - export ANDROID_HOME=~/android-sdk-linux
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
  - sdkmanager "tools" "platform-tools" "build-tools;28.0.3" "platforms;android-28" > /dev/null

before_script:
  - _JAVA_OPTIONS=

script:
  - ./gradlew build testDownstream -PcheckJava8Compatibility -s && ./gradlew ciPerformRelease -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
