# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build with travis caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Remove often changing files to prevent cache re-upload on no changes in dependencies
before_cache:
# pom, xml and jar files are known not to change
# assume non-whitelisted extensions are changing
# (this will include .lock, .bin, .metadata and potential future additions to gradle's caches folder)
  - find $HOME/.gradle/caches -type f -not \( -iname \*.pom -o -iname \*.jar -o -iname \*.xml \) -delete
# jar files which change
  - rm -fr $HOME/.gradle/caches/*/workerMain/gradle-worker.jar
# xml files which change
  - find $HOME/.gradle/caches/modules-2 -name ivy.xml -delete
# remove left over empty directories
  - find $HOME/.gradle/caches -type d -empty -delete

language: java

jdk:
  - oraclejdk8

#Skipping install step to avoid having Travis run arbitrary './gradlew assemble' task
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install:
  - true

#Don't build tags
branches:
  except:
  - /^v\d/

#Build and perform release (if needed)
script:
  - ./gradlew build -s && ./gradlew ciPerformRelease